Support for Python3 and Kodi 19
XBMCil/service.subtitles.ktuvit pull request #2
Opened 2019-12-02 07:01 UTC by sagiben

tested only on Kodi 19.

2019-12-02 08:00 UTC, CaTzil requested changes

2019-12-02 08:00 UTC, CaTzil commented on addon.xml
> +    <import addon="xbmc.python" version="2.25.0"/>
Should we specify here v 3?

2019-12-02 08:00 UTC, CaTzil commented
Thanx for the PR!

Is this change supported by Kodi 18?

2019-12-02 08:07 UTC, sagiben commented
Did not have time to check on Kodi 18, will try to do it later. 
But Kodi 18 should support both python2.7 and python3

2019-12-02 08:08 UTC, merged

2019-12-02 08:09 UTC, CaTzil commented
I will check it later today, thank you! :]

2019-12-07 09:47 UTC, CaTzil commented
Hi, I've tested it on kodi 18, it is fails on 
```
  File "/Users/***/Library/Application Support/Kodi/addons/service.subtitles.screwzira/service.py", line 5, in <module>
        import urllib.parse
        ImportError: No module named parse
```
Can you help with it?

2019-12-07 16:59 UTC, sagiben commented
> Hi, I've tested it on kodi 18, it is fails on
> 
> ```
>   File "/Users/***/Library/Application Support/Kodi/addons/service.subtitles.screwzira/service.py", line 5, in <module>
>         import urllib.parse
>         ImportError: No module named parse
> ```
> 
> Can you help with it?

Sure. on it